# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

error do |lane, exception, options|
  discord_notifier(
   webhook_url: ENV['DISCORD_WEBHOOK_URL'],
    title: "Error occurred",
    description: "Error occurred #{exception}",
  )
end

platform :android do
  desc "Build appbundle"
  lane :build do
    sh("flutter", "clean")
    Dir.chdir("../../") do
      sh("flutter", "pub", "get")
    end
    sh("flutter", "build", "appbundle")
  end

  lane :deploy do
    discord_notifier(
    webhook_url: ENV['DISCORD_WEBHOOK_URL'],
    title: "Android Deploy Build started",
    description: "Android Deploy Build started",
    )
    build
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,  
      skip_upload_images: true,  
      skip_upload_screenshots: true,  
    )
    discord_notifier(
    webhook_url: ENV['DISCORD_WEBHOOK_URL'],
    title: "New build uploaded to play store",
    description: "New build uploaded to play store",
    )
  end

  lane :deploy_beta do
    discord_notifier(
    webhook_url: ENV['DISCORD_WEBHOOK_URL'],
    title: "Android Beta Build started",
    description: "Android Beta Build started",
    )
    build
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "alpha",
      skip_upload_metadata: true,  
      skip_upload_images: true,  
      skip_upload_screenshots: true,  
    )
    discord_notifier(
    webhook_url: ENV['DISCORD_WEBHOOK_URL'],
    title: "New build uploaded to play store",
    description: "New build uploaded to play store",
    )
  end
  
end
